baseURL = "https://ryuusei.moe/"
languageCode = "en-us"
title = "Ryuusei"

[params]
  description = "An unofficial AniList client for iOS"
  logo = "android-chrome-512x512.png"

[author]
  name = "Kyle Lanchman"
  twitter = "klanchman"
