[[redirects]]
  from = "/forum-thread"
  to = "https://anilist.co/forum/thread/8228"

[[redirects]]
  from = "/delete-account"
  to = "https://anilist.co/settings/account"

[build]
command = "hugo --gc --minify --baseURL $URL"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture --baseURL $DEPLOY_PRIME_URL"

[context.production.environment]
  HUGO_VERSION = "0.102.3"
  HUGO_ENV = "production"
